[project]
name = "hackathon"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "fastapi[standard]>=0.115.8",
]
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
